[context.production.environment]
  HUGO_VERSION = "0.72.0"

[build]
publish = "public"
command = "hugo --gc --minify"

[[redirects]]
  from = "https://www.studioholloway.com/microblading-vs-microshading"
  to = "https://www.studioholloway.com/microblading"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://www.studioholloway.com/cest-quoi-le-microblading"
  to = "https://www.studioholloway.com/microblading"
  status = 301
  force = true #COMMENT: ensure that we always redirect

  [[redirects]]
  from = "https://www.studioholloway.com/cest-quoi-la-difference-entre-le-microblading-et-les-sourcils-permanents/"
  to = "https://www.studioholloway.com/microblading"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404